services:
  client:
    container_name: knd_client
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: https://kndenergen.co.kr
        NEXT_PUBLIC_API_BASE_URL: /api
    expose:
      - "3306"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=/api
      - NEXT_PUBLIC_API_URL=https://kndenergen.co.kr
    networks:
      edge:
        aliases:
          - knd-client
    restart: unless-stopped

  server:
    container_name: knd_server
    build:
      context: ./server
      dockerfile: Dockerfile
      x-bake:
        platforms:
          - linux/amd64
    expose:
      - "8080"
    environment:
      - NODE_ENV=production
      - DOCKER_BUILDKIT=1
      - SPRING_DATASOURCE_URL=jdbc:mariadb://db:3306/knd?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=knd
      - SPRING_DATASOURCE_PASSWORD=kndpw
    env_file:
      - ./server/.env
    networks:
      edge:
        aliases:
          - knd-server
    restart: unless-stopped

networks:
  edge:
    external: true
